### ISSUE TITLE
Was muss ich tun, damit das Automapping funktioniert?

### ISSUE THREAD

**Issue by Gerhard-Wonner** [MorgenGrauen/mg-mudlet#2]
Hallo, ich bekomme das Automapping leider nicht ans laufen. Leider erklärt ihr in eurer Readme nicht, was ich tun muss, damit die Karte wirklich mitgezeichnet wird.
Vielen Dank!

**Comment by Kebap** [comment]
Hallo, bitte tippe im Spiel einmal `mhilfe` für eine ausführliche Erklärung des Automappings.
Es gibt im MorgenGrauen auch eine Ebene namens `-mudlet` für kurzfristigere Antworten.

**Comment by Gerhard-Wonner** [comment]
Hallo @Kebap 
Vielen Dank für deine Hilfe! Das hat jetzt schon recht gut funktioniert und ich eine ganze weile erfolgreich gemapped und auch neue Gebiete nach Teleportationen angelegt. Leider habe ich jetzt ein Problem, welches nicht unter mhilfe beschrieben wird:
Wenn ich mich auslogge und anschließend wieder einlogge scheint der Mapper meine Position verloren zu haben. Der Cursor, welcher die Position des Spielers anzeigt, bewegt sich nichtmehr, wenn ich in einen angrenzenden Raum wechsle. Was kann ich tun, damit der Cursor mir wieder folgt?

**Comment by Kebap** [comment]
Einen solchen Fehler kenne ich noch nicht. Es könnte mehrere Ursachen geben, an denen es schief läuft.
Empfängst du noch GMCP Daten? Tippe zum Test einmal: `lua display(gmcp.MG.room.info)` 
Siehst du die ID des Raumes? Ändert sich die Ausgabe, wenn du den Raum wechselst?
Vermutlich wäre die Fehlereingrenzung schneller mit direkter Beratung im Spiel.
