### ISSUE TITLE
Kann ich mir die "Stubs" der Ausgänge anzeigen lassen?

### ISSUE THREAD

**Issue by Gerhard-Wonner** [MorgenGrauen/mg-mudlet#3]
Hallo,
vielen Dank für die tollen Tools! :-)
Ich wollte mal nachfragen, ob es möglich ist, dass der Mapper auf der Karte auch diejenigen Ausgänge andeutet (z.B. als kurze Striche in der jeweiligen Richtung), welche ich noch nicht verwendet habe.
Ich habe nämlich das Problem, dass ich beim betrachten einer vom Mapper erstellten Karte nicht sehen kann, wo es noch unerforschte Gebiete zu erkunden gibt.
Vielen Dank schon mal!

**Comment by Kebap** [comment]
Hallo und sorry für die späte Antwort!
Zunächst mal danke für den tollen Vorschlag! :-)
Also aktuell gibt es dafür noch keine Einstellung, so dass es nicht ohne weiteres direkt möglich ist. 
Im Grunde bietet Mudlet dafür aber die passende Unterstützung an. Es müsste nur in dem MG Mapper Code von @talanis85 hinzugefügt werden. Das könnte theoretisch jeder machen, und dann können wir die Erweiterung hier mit einbauen und wieder veröffentlichen. 
Alternativ gibt es den Plan, den neuen offiziellen Mudlet generic mapper (den es zu Talanis Zeit noch nicht gab) fürs MG anzupassen, und die ebenfalls neuen Gmcp Infos des MG für genauere Karten zu benutzen. Das wäre die langfristigere Variante, aber über diesen Status noch nicht heraus, und somit bislang genau das: Ein Plan.
Sorry, dass ich diesmal keine hilfreichere Antwort für dich habe!

**Comment by Kebap** [comment]
Hallo @Gerhard-Wonner!
Probier bei Gelegenheit gerne einmal die neue Version und lass uns wissen, wie dir die "Stubs" der Ausgänge hier inzwischen gefallen.
Bis dahin schließe ich dieses Thema. Melde dich aber einfach wieder, wenn noch etwas aufkommen sollte.
